name: pdf_to_excel_converter
description: Applicazione Flutter per convertire PDF in Excel
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^5.3.2
  path_provider: ^2.0.15
  permission_handler: ^10.4.5
  excel: ^2.1.0
  syncfusion_flutter_pdf: ^20.4.54
  share_plus: ^6.0.0

dependency_overrides:
  win32: ^5.0.2
  syncfusion_flutter_core: ^20.4.54

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/test_files/